### ISSUE TITLE
ClassCastException: A$ViewHolder cannot be cast to B$ViewHolder

### ISSUE THREAD

**Issue by winsonlim** [yqritc/RecyclerView-MultipleViewTypesAdapter#4]
Hey,

I am using setBinder(0, newBinder) to replace the first item on my adapter (ListBindAdapter), and then called notifyBinderItemRangeChanged(newBinder, 0, 1). It is unable to replace the first DataBinder.

It crashed at com.yqritc.recyclerviewmultipleviewtypesadapter.DataBindAdapter.onBindViewHolder(DataBindAdapter.java:21)

**Comment by yqritc** [comment]
After reproducing the crash and checking its stack trace, I realised that the current version of library cannot dynamically change the binder after initialising binders because RecyclerView cache the mapping of the viewtype and viewHolder once created. 
I will try to fix its problem, but I needs some time to understand more about cache and recycle mechanism of RecyclerView.

The current workaround is to create all binders at initialisation and control the item counts of those binders.  (*items will become invisible by setting item counts zero)

**Comment by yqritc** [comment]
I could not get solution to fix this problem. 
In order to prevent the confusion, I removed binder setter functions in v1.1.0
